/// <reference types='vitest' />
import { mkdirSync, writeFileSync } from 'fs';
import { join } from 'path';
import type { Plugin } from 'vite';
import { defineConfig, loadEnv } from 'vite';
import react from '@vitejs/plugin-react';
import { nxViteTsPaths } from '@nx/vite/plugins/nx-tsconfig-paths.plugin';
import { nxCopyAssetsPlugin } from '@nx/vite/plugins/nx-copy-assets.plugin';

/** Keep in sync with `firebase` in package.json (compat CDN URLs). */
const FIREBASE_SW_COMPAT_VERSION = '11.10.0';

function firebaseMessagingSwPlugin(rootDir: string): Plugin {
  return {
    name: 'write-firebase-messaging-sw',
    configResolved(config) {
      const env = loadEnv(config.mode, rootDir, '');
      const keys = [
        'VITE_FIREBASE_API_KEY',
        'VITE_FIREBASE_AUTH_DOMAIN',
        'VITE_FIREBASE_PROJECT_ID',
        'VITE_FIREBASE_STORAGE_BUCKET',
        'VITE_FIREBASE_MESSAGING_SENDER_ID',
        'VITE_FIREBASE_APP_ID',
      ] as const;
      const outDir = join(rootDir, 'public');
      mkdirSync(outDir, { recursive: true });
      const outPath = join(outDir, 'firebase-messaging-sw.js');

      if (keys.some((k) => !env[k]?.trim())) {
        const stub = `/* Generated by Vite — add VITE_FIREBASE_* to apps/frontend/.env for FCM background handling. */
self.addEventListener('install', (e) => self.skipWaiting());
self.addEventListener('activate', (e) => e.waitUntil(self.clients.claim()));
`;
        writeFileSync(outPath, stub, 'utf8');
        return;
      }

      const cfg = {
        apiKey: env.VITE_FIREBASE_API_KEY,
        authDomain: env.VITE_FIREBASE_AUTH_DOMAIN,
        projectId: env.VITE_FIREBASE_PROJECT_ID,
        storageBucket: env.VITE_FIREBASE_STORAGE_BUCKET,
        messagingSenderId: env.VITE_FIREBASE_MESSAGING_SENDER_ID,
        appId: env.VITE_FIREBASE_APP_ID,
      };
      const v = FIREBASE_SW_COMPAT_VERSION;
      const sw = `/* Generated by Vite from env — do not edit */
importScripts('https://www.gstatic.com/firebasejs/${v}/firebase-app-compat.js');
importScripts('https://www.gstatic.com/firebasejs/${v}/firebase-messaging-compat.js');
firebase.initializeApp(${JSON.stringify(cfg)});
const messaging = firebase.messaging();
messaging.onBackgroundMessage((payload) => {
  const n = payload.notification;
  if (!n) return;
  self.registration.showNotification(n.title || 'Notification', {
    body: n.body || '',
    icon: n.icon,
  });
});
`;
      writeFileSync(outPath, sw, 'utf8');
    },
  };
}

export default defineConfig(() => ({
  root: import.meta.dirname,
  cacheDir: '../../node_modules/.vite/apps/frontend',
  server: {
    port: 4200,
    host: 'localhost',
  },
  preview: {
    port: 4200,
    host: 'localhost',
  },
  plugins: [
    react(),
    nxViteTsPaths(),
    nxCopyAssetsPlugin(['*.md']),
    firebaseMessagingSwPlugin(import.meta.dirname),
  ],
  // Uncomment this if you are using workers.
  // worker: {
  //   plugins: () => [ nxViteTsPaths() ],
  // },
  build: {
    outDir: '../../dist/apps/frontend',
    emptyOutDir: true,
    reportCompressedSize: true,
    commonjsOptions: {
      transformMixedEsModules: true,
    },
  },
}));
